export const colors = {
  primary: '#FF6B6B',
  primaryLight: '#FF8E8E',
  primaryDark: '#E55555',
  secondary: '#4ECDC4',
  secondaryLight: '#7EDDD6',
  background: '#FFF9F5',
  surface: '#FFFFFF',
  textPrimary: '#2C3E50',
  textSecondary: '#7F8C8D',
  textTertiary: '#BDC3C7',
  success: '#27AE60',
  successLight: '#E8F8F0',
  accent: '#F39C12',
  accentLight: '#FEF3E2',
  error: '#E74C3C',
  errorLight: '#FDEDEC',
  border: '#ECE8E4',
  tabBarInactive: '#BDC3C7',
} as const;
